### ISSUE TITLE
Show "last updated"/"next update" date on the profile page

### ISSUE THREAD

**Issue by njnash** [psu-stewardship/researcher-metadata#54] opened 2020-05-12 14:42 UTC
This would just be static content that indicates when the last data import occurred and when the next one is scheduled to occur.

Aha! Link: https://penn-state-university-libraries.aha.io/features/MDDB-5

**Comment by EricDurante** [comment] 2020-06-04 15:00
Duplicate of https://github.com/psu-stewardship/researcher-metadata/issues/19

**Closed by EricDurante** 2020-06-04 15:00 UTC
