### ISSUE TITLE
Publication without an authorship for the RMD user whose Activity Insight data provided the publication data

### ISSUE THREAD

**Issue by anaelizabethenriquez** [psu-stewardship/researcher-metadata#407] opened 2021-11-30 19:38 UTC
We just received the first publication claim request. I have approved it already.

The publication in question is 259777, and the user is sfh5482. There are three authors on the paper, only one of whom (sfh5482) is at Penn State. The publication data came from an Activity Insight import. So far as I can tell, neither of the other authors have ever had Penn State affiliations, so the Activity Insight data would have come from sfh5482. However, sfh5482 did not have an authorship on this publication. They had to claim it. (I approved the claim, so they have an authorship now.)

I would have expected sfh5482 to have an authorship for this publication already. Is something going wrong here?

**Comment by EricDurante** [comment] 2021-11-30 21:28
As far as I can tell, nothing is going wrong beyond this specific example. If I look at Simon's [current data](https://webservices.digitalmeasures.com/login/service/v4/SchemaData/INDIVIDUAL-ACTIVITIES-University/USERNAME:SFH5482) in Activity Insight, I do see what looks like a representation of this publication. However, it's not the same representation that RMD imported and which Simon then claimed in RMD. The Activity Insight ID is different, and the title is slightly different as well - "Secret Shoppers Find Access To Providers And Network Accuracy Lacking For Those In Marketplace And Commercial Plans." in AI vs. "California Secret Shoppers Find Access To Physicians And Network Accuracy Are Lacking For Those In Marketplace And Commercial Plans" in RMD. If I search the current AI data for this AI publication ID that was imported into RMD, I don't find it. I assume that means that the publication metadata that was originally imported into RMD from AI has now been deleted from AI and replaced with the new set of metadata that I'm seeing now.

To make this even more confusing, if I look at Simon's whole list of publications in RMD, I see what looks like [a couple of other representations](https://metadata.libraries.psu.edu/admin/user/14274#bulk_ids_246897) of this same publication which have apparently not been automatically grouped for duplicate resolution. One of these was imported form Pure, and the other was imported from AI. The one from AI _does_ match the publication metadata that's currently in AI.

I'm not sure how the publication record that Simon claimed came to be in RMD without Simon listed as an author, but that almost seems moot since we do appear to have another copy of the metadata from AI wherein he _is_ listed as an author.

In any case, all three of these now show up in Simon's public RMD profile, which is almost certainly not what we want. It's odd that Simon searched out this publication and claimed what appears to be a third duplicate of it even though two other copies of it were already in his list of publications.

Actually what most surprises me, given that the titles are so similar and the publication year is the same,  is that these three publications weren't grouped as duplicates in RMD.

**Comment by EricDurante** [comment] 2021-11-30 21:40
So I guess that we can chalk the current state of the RMD metadata up to some bad data that was imported from AI previously and to duplicate titles that weren't quite similar enough to match. I'm not sure that we'll be able to explain it better than that at this point. To me, the really curious thing is _why_ Simon claimed this publication record..

**Comment by anaelizabethenriquez** [comment] 2021-11-30 21:50
> To me, the really curious thing is why Simon claimed this publication record..
My guess would be that he searched for his own name on the Search page. But, it's just a guess.

**Comment by EricDurante** [comment] 2021-11-30 21:52
Yep! I just thought of that too. The author search queries by `ContributorName` rather than `User`, and his name was listed on that publication even though he wasn't linked as an author. I think you nailed it.

**Comment by EricDurante** [comment] 2021-11-30 22:03
So maybe all that we need to do to resolve this issue is to manually group and merge those three duplicate publications? 

Hopefully we won't encounter many more situations like this, but at least the "claim publication" feature allowed a user to bring some bad data to our attention in this case.

**Closed** 2021-12-01 20:54 UTC
Labels: bug
