### ISSUE TITLE
OA Button Importer JSON::ParserError:  TypeError: options.url.replace is not a function at Object.API.service.oab.find

### ISSUE THREAD

**Issue by cswalina** [psu-stewardship/researcher-metadata#86] opened 2020-08-17 13:39 UTC
[Bugsnag](https://app.bugsnag.com/west-arete/psu-research-metadata/errors/5f37d6932c8fb60017a6670d?event_id=5f3a090a005bfec5d6ea0000&i=sk&m=ra)

This error got thrown well into the latest OA import. I restarted the OA import job by skipping over the offending publication ( id=241626 ) by setting its open_access_button_last_checked_at attribute. I'll do the same for any additional occurences and list them here as well. Part of addressing this issue will require resetting "open_access_button_last_checked_at" to nil for these publications.

**Comment by ajkiessl** [comment] 2022-06-03 18:38
@anaelizabethenriquez This one can be closed.  I don't see that record either.  It may have been merged with another record.  I also don't see that specific error anywhere in our recent importer error logs.  We do still get some JSON::ParserErrors during our OAB imports, but it looks like they are caused by 502 Bad Gateway errors.  These are just network errors and are temporary.

**Closed by ajkiessl** 2022-06-03 18:38 UTC
