### ISSUE TITLE
Make non-duplicate Activity Insight publication records visible in production data

### ISSUE THREAD

**Issue by njnash** [psu-stewardship/researcher-metadata#42] opened 2020-05-12 14:32 UTC
As discussed here:  https://basecamp.com/1759334/projects/15421427/messages/88508508

Our initial workaround for the problem of duplicate publication records was to simply hide all of the publication records that were imported from Activity Insight. We made this decision because Pure had a much larger and partially overlapping (hence the duplication) set of publication data. We implemented this workaround before we had a good way of finding suspected duplicate records. Now that we have identified a lot of duplicates, we think that we can go ahead and unhide any publication records that were imported from Activity Insight and that do not have any known duplicates. We should do this in the production database so that we can make as much publication data as possible available to our users.

Aha! Link: https://penn-state-university-libraries.aha.io/features/MDDB-17

**Comment by EricDurante** [comment] 2020-06-04 15:22
This turned out to be more complicated than what's described above. After a manual sampling of the data, it became apparent that our method for detecting duplicate publications is too strict, and it misses a lot of actual duplicates. We probably need to do the following (which may be better described as several separate but related issues):

1. We should probably finish manually resolving the duplicates that we have already detected. This can be done relatively quickly because we're pretty sure that this set contains very few false-positives.
2. We need to "cast a wider net" to find more actual duplicates even if this also risks a lot more false-positives. We should manually sample some data to see if it seems like we're finding most or all of the actual duplicates with our new method. This will give us an idea of how many more duplicates (including false-positives) there are to resove. We're also not currently using the limited DOI data that we have to try to automatically find or rule out duplicates, so we should incorporate this.
3. We need a mechanism within the admin interface to manually resolve false-positive duplicates so that they are flagged and don't appear again in the future.
4. We sometimes end up with groups of duplicate publications wherein not all of the publications are actually duplicates of each other, but some of them are. There may be two or more actual groups of duplicates within a single group that we've identified automatically, and then there also may or may not be other individual publications that are false-positives that aren't actually a duplicate of any of the other publications in the group. So, we also need a mechanism in the admin interface whereby an admin can "regroup" publications from within an existing group or otherwise deal with individual publications within a duplicate group on a case-by-case basis rather than either merging them all together into one or rejecting them all as false-positivies.

Once we've done all of this and the admins have resolved the second round of automatically-detected duplicates, we can be fairly confident that most of the duplicates have been eliminated, and we'd be able to show the Activity Insight publication data.

**Closed** 2020-08-12 20:26 UTC
