### ISSUE TITLE
Single department displayed with "other organizations" listed elsewhere

### ISSUE THREAD

**Issue by njnash** [psu-stewardship/researcher-metadata#51] opened 2020-05-12 14:40 UTC
Aha! Link: https://penn-state-university-libraries.aha.io/features/MDDB-8

**Comment by EricDurante** [comment] 2020-06-04 15:31
Duplicate of https://github.com/psu-stewardship/researcher-metadata/issues/21

**Closed by EricDurante** 2020-06-04 15:31 UTC
